# Generated by Django 5.0.6 on 2024-05-27 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='Arret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('commentaire', models.TextField(blank=True, max_length=200, null=True)),
                ('heure_et_minute_du_debut', models.TimeField()),
                ('heure_et_minute_de_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nb_op', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_secteur', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlageDeTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.TimeField()),
                ('fin', models.TimeField()),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ac', models.CharField(max_length=15, unique=True)),
                ('date_production', models.DateTimeField()),
                ('ligne',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.ligne')),
                ('secteur',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.secteur')),
            ],
        ),
        migrations.AddField(
            model_name='ligne',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.secteur'),
        ),
        migrations.CreateModel(
            name='Subtype_arret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('arret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.arret')),
            ],
        ),
        migrations.CreateModel(
            name='Moyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.ligne')),
                ('type_arret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.arret')),
                ('subtype_arret',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.subtype_arret')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_subtype_arret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('arret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.arret')),
                ('sub_type_arret',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.subtype_arret')),
            ],
        ),
    ]
