# Generated by Django 5.0.6 on 2024-05-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail_subtype_arret',
            new_name='DetailSubTypeArret',
        ),
        migrations.RenameModel(
            old_name='Subtype_arret',
            new_name='SubTypeArret',
        ),
    ]
