# Generated by Django 5.0.6 on 2024-05-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0002_rename_detail_subtype_arret_detailsubtypearret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code_ac',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
