# Generated by Django 5.0.6 on 2024-05-27 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0003_alter_produit_code_ac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne',
            name='nb_op',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='date_production',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='ligne',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='secteur',
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_production', models.DateTimeField()),
                ('nb_op', models.IntegerField(default=2)),
                ('ligne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.ligne')),
                ('secteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.secteur')),
            ],
        ),
    ]
