# Generated by Django 5.0.6 on 2024-05-27 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0004_remove_ligne_nb_op_remove_produit_date_production_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='nb_op',
            new_name='nombre_operateur',
        ),
        migrations.AddField(
            model_name='production',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.equipe'),
        ),
    ]
