# Generated by Django 5.0.6 on 2024-05-29 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0006_rename_heure_et_minute_de_fin_arret_heure_et_minute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moyen',
            name='type_arret',
        ),
        migrations.AddField(
            model_name='production',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='detail_sub_type_arret',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.detailsubtypearret'),
        ),
        migrations.AddField(
            model_name='production',
            name='moyen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.moyen'),
        ),
        migrations.AddField(
            model_name='production',
            name='subtype_arret',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.subtypearret'),
        ),
        migrations.AddField(
            model_name='production',
            name='type_arret',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.arret'),
        ),
        migrations.AlterField(
            model_name='moyen',
            name='ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.ligne'),
        ),
        migrations.AlterField(
            model_name='moyen',
            name='subtype_arret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.subtypearret'),
        ),
    ]
