# Generated by Django 5.0.6 on 2024-05-30 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0008_alter_arret_heure_et_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='moyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.moyen'),
        ),
    ]
