# Generated by Django 5.0.6 on 2024-05-30 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0009_alter_production_moyen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=155)),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='defaults',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='duree',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='face_inferieure_du_produit',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='face_superieure_du_produit',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.produit'),
        ),
        migrations.AddField(
            model_name='production',
            name='quantity_fs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='detail_sub_type_arret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.detailsubtypearret'),
        ),
        migrations.AlterField(
            model_name='production',
            name='subtype_arret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.subtypearret'),
        ),
        migrations.AddField(
            model_name='production',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.client'),
        ),
    ]
