# Generated by Django 5.0.6 on 2024-05-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0010_client_production_defaults_production_duree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='duree',
        ),
        migrations.AddField(
            model_name='production',
            name='duree_heure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='duree_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
