# Generated by Django 5.0.6 on 2024-05-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0011_remove_production_duree_production_duree_heure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='face_inferieure_du_produit',
            new_name='face_du_produit',
        ),
        migrations.RemoveField(
            model_name='production',
            name='face_superieure_du_produit',
        ),
    ]
