# Generated by Django 5.0.6 on 2024-06-01 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0012_rename_face_inferieure_du_produit_production_face_du_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='production',
            name='detail_sub_type_arret',
        ),
        migrations.RemoveField(
            model_name='production',
            name='duree_heure',
        ),
        migrations.RemoveField(
            model_name='production',
            name='duree_minute',
        ),
        migrations.RemoveField(
            model_name='production',
            name='moyen',
        ),
        migrations.RemoveField(
            model_name='production',
            name='subtype_arret',
        ),
        migrations.RemoveField(
            model_name='production',
            name='type_arret',
        ),
        migrations.CreateModel(
            name='ArretDeProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_heure', models.IntegerField(blank=True, null=True)),
                ('duree_minute', models.IntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('detail_sub_type_arret', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.detailsubtypearret')),
                ('moyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.moyen')),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.production')),
                ('subtype_arret', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.subtypearret')),
                ('type_arret', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.arret')),
            ],
        ),
    ]
