# Generated by Django 5.0.6 on 2024-06-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0013_remove_production_commentaire_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arretdeproduction',
            old_name='duree_heure',
            new_name='duree_en_heure',
        ),
        migrations.RenameField(
            model_name='arretdeproduction',
            old_name='duree_minute',
            new_name='duree_en_minute',
        ),
    ]
