# Generated by Django 5.0.6 on 2024-06-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0014_rename_duree_heure_arretdeproduction_duree_en_heure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='face_du_produit',
            field=models.CharField(blank=True, choices=[('1', 'FACE 1'), ('2', 'FACE 2')], max_length=10, null=True),
        ),
    ]
