# Generated by Django 5.0.6 on 2024-06-05 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0019_production_quantity_fc'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempsDeCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcm', models.DecimalField(decimal_places=2, help_text='Temps de cycle moyen en Heure', max_digits=10)),
                ('face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.faceproduit')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.produit')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.secteur')),
            ],
        ),
    ]
