# Generated by Django 5.0.6 on 2024-06-08 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0020_tempsdecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='defaults',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='face_produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.faceproduit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='quantity_fc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='quantity_fs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempsdecycle',
            name='face',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.faceproduit'),
        ),
    ]
