# Generated by Django 5.0.6 on 2024-06-08 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0021_produit_defaults_produit_face_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.client'),
        ),
        migrations.AlterField(
            model_name='production',
            name='face_du_produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.faceproduit'),
        ),
        migrations.AlterField(
            model_name='production',
            name='heure_debut',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='heure_fin',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.produit'),
        ),
    ]
