# Generated by Django 5.0.6 on 2024-06-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0022_alter_production_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempsdecycle',
            name='tcm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Temps de cycle moyen en Heure', max_digits=10),
        ),
    ]
