# Generated by Django 5.0.6 on 2024-06-08 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0025_remove_tempsdecycle_produit_tempsdecycle_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsdecycle',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.produit'),
        ),
    ]
