# Generated by Django 5.0.6 on 2024-06-08 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0027_alter_tempsdecycle_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arretdeproduction',
            name='duree_en_heure',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='arretdeproduction',
            name='duree_en_minute',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='ArretDeTypeChangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('detail_type_arret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.detailsubtypearret')),
            ],
        ),
    ]
