# Generated by Django 5.0.6 on 2024-06-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0028_alter_arretdeproduction_duree_en_heure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arretdeproduction',
            name='duree_en_heure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arretdeproduction',
            name='duree_en_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
