# Generated by Django 5.0.6 on 2024-06-08 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0029_alter_arretdeproduction_duree_en_heure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=155)),
            ],
        ),
        migrations.AddField(
            model_name='arretdeproduction',
            name='changement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.arretdetypechangement'),
        ),
        migrations.AddField(
            model_name='arretdeproduction',
            name='intervenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.intervenant'),
        ),
    ]
