# Generated by Django 5.0.6 on 2024-06-08 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0030_intervenant_arretdeproduction_changement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arretdeproduction',
            name='changement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.arretdetypechangement'),
        ),
        migrations.AlterField(
            model_name='arretdeproduction',
            name='intervenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.intervenant'),
        ),
    ]
