# Generated by Django 5.0.6 on 2024-06-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0031_alter_arretdeproduction_changement_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArretDeTypeChangement',
            new_name='Changement',
        ),
    ]
