# Generated by Django 5.0.6 on 2024-06-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0032_rename_arretdetypechangement_changement'),
    ]

    operations = [
        migrations.AddField(
            model_name='arretdeproduction',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
