# Generated by Django 5.0.6 on 2024-06-15 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0034_remove_produit_defaults_remove_produit_face_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='client',
        ),
        migrations.RemoveField(
            model_name='production',
            name='defaults',
        ),
        migrations.RemoveField(
            model_name='production',
            name='face_du_produit',
        ),
        migrations.RemoveField(
            model_name='production',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='production',
            name='heure_fin',
        ),
        migrations.RemoveField(
            model_name='production',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='production',
            name='quantity_fc',
        ),
        migrations.RemoveField(
            model_name='production',
            name='quantity_fs',
        ),
        migrations.CreateModel(
            name='ProductionStepTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField(null=True)),
                ('heure_fin', models.TimeField(null=True)),
                ('quantity_fs', models.IntegerField(blank=True, null=True)),
                ('quantity_fc', models.IntegerField(blank=True, null=True)),
                ('defaults', models.IntegerField(default=0, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.client')),
                ('face_du_produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.faceproduit')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.production')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.produit')),
            ],
        ),
    ]
