# Generated by Django 5.0.6 on 2024-06-19 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0037_rename_production_tempsdecycle_production_step_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsdecycle',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.client'),
        ),
        migrations.AddField(
            model_name='tempsdecycle',
            name='commentaire',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='tempsdecycle',
            name='equipement_menant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.moyen'),
        ),
    ]
