# Generated by Django 5.0.6 on 2024-06-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0038_tempsdecycle_client_tempsdecycle_commentaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempsdecycle',
            name='production_step_two',
        ),
    ]
