# Generated by Django 5.0.6 on 2024-06-23 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0039_remove_tempsdecycle_production_step_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifChangeOver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changement_produit_commun', models.FloatField()),
                ('changement_version', models.FloatField()),
                ('changement_produit_specifique', models.FloatField()),
                ('changement_face', models.FloatField()),
                ('commentaire', models.CharField(max_length=155)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.client')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.ligne')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.secteur')),
            ],
        ),
    ]
