# Generated by Django 5.0.6 on 2024-06-26 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0040_objectifchangeover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectifchangeover',
            name='changement_face',
        ),
        migrations.RemoveField(
            model_name='objectifchangeover',
            name='changement_produit_commun',
        ),
        migrations.RemoveField(
            model_name='objectifchangeover',
            name='changement_produit_specifique',
        ),
        migrations.RemoveField(
            model_name='objectifchangeover',
            name='changement_version',
        ),
        migrations.RemoveField(
            model_name='objectifchangeover',
            name='commentaire',
        ),
        migrations.AddField(
            model_name='objectifchangeover',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.produit'),
        ),
        migrations.CreateModel(
            name='TypeDeChangementDeObjectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('changement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.changement')),
                ('objectif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creationpuce.objectifchangeover')),
            ],
        ),
    ]
