# Generated by Django 5.0.6 on 2024-06-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0042_objectifchangeover_face_du_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedechangementdeobjectif',
            name='valeur',
            field=models.FloatField(null=True),
        ),
    ]
