# Generated by Django 5.0.6 on 2024-06-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0043_alter_typedechangementdeobjectif_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedechangementdeobjectif',
            name='valeur',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
