# Generated by Django 5.0.6 on 2024-06-27 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0045_alter_typedechangementdeobjectif_objectif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedechangementdeobjectif',
            name='objectif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='creationpuce.objectifchangeover'),
        ),
    ]
