# Generated by Django 5.0.6 on 2024-07-04 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0047_alter_moyen_heure_debut_alter_moyen_heure_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempsdecycle',
            name='secteur',
        ),
        migrations.AddField(
            model_name='tempsdecycle',
            name='ligne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.ligne'),
        ),
    ]
