# Generated by Django 5.0.6 on 2024-07-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0048_remove_tempsdecycle_secteur_tempsdecycle_ligne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectifchangeover',
            name='face_du_produit',
        ),
    ]
