# Generated by Django 5.0.6 on 2024-07-04 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0049_remove_objectifchangeover_face_du_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='famille',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.famille'),
        ),
    ]
