# Generated by Django 5.0.6 on 2024-07-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0050_famille_produit_famille'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.client'),
        ),
    ]
