# Generated by Django 5.0.6 on 2024-07-15 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationpuce', '0052_rename_equipement_menant_tempsdecycle_moyen'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectifchangeover',
            name='famille',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='creationpuce.famille'),
        ),
    ]
